using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis;
using System.Text;

namespace AutoEventBus;

[Generator(LanguageNames.CSharp)]
public class AttributeSourceGenerator : IIncrementalGenerator
{
    private static readonly string Source =
$@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by {ThisAssembly.Project.PackageProjectUrl}
//     Version: {ThisAssembly.Project.Version}
//     SHA: {ThisAssembly.Git.Sha}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if AUTOEVENTBUS_EMBED_ATTRIBUTES
namespace AutoEventBus
{{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{ThisAssembly.Project.AssemblyName}"", ""{ThisAssembly.Project.Version}"")]
    [global::System.AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    [global::System.Diagnostics.Conditional(""AUTOEVENTBUS_USAGES"")]
    internal sealed class SubscriberAttribute : System.Attribute
    {{
        [global::System.Runtime.CompilerServices.CompilerGenerated]
        public SubscriberAttribute()
        {{
        }}
    }}
}}
#endif";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static c =>
        {
            c.AddSource("AutoEventBusAttribute.g.cs", SourceText.From(Source, Encoding.UTF8));
        });
    }
}
