//HintName: AutoEventBusAttribute.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoEventBus.git
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if AUTOEVENTBUS_EMBED_ATTRIBUTES
namespace AutoEventBus
{
	[System.Runtime.CompilerServices.CompilerGenerated]
	[System.AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
	[System.Diagnostics.Conditional(""AUTOEVENTBUS_USAGES"")]
	internal sealed class SubscriberAttribute : System.Attribute
	{
		[System.Runtime.CompilerServices.CompilerGenerated]
		public AutoConstructAttribute()
		{
		}
	}
}
#endif
