//HintName: AutoEventBusAttribute.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoEventBus
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if AUTOEVENTBUS_EMBED_ATTRIBUTES
namespace AutoEventBus
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("AutoEventBus", "0.0.0")]
    [global::System.AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    [global::System.Diagnostics.Conditional("AUTOEVENTBUS_USAGES")]
    internal sealed class SubscriberAttribute : System.Attribute
    {
        [global::System.Runtime.CompilerServices.CompilerGenerated]
        public SubscriberAttribute()
        {
        }
    }
}
#endif
