//HintName: EventBus_Send__Int32.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public static partial class EventBus
{
	public static void Send(int value)
	{
		lock (_subList_Basic)
		{
#if NET5_0_OR_GREATER
			foreach (var receiver in System.Runtime.InteropServices.CollectionsMarshal.AsSpan(_subList_Basic))
#else
			foreach (var receiver in _subList_Basic)
#endif
			{
				receiver.Do(value);
			}
		}
	}
}
