//HintName: EventBus_ClassA.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoEventBus.git
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

public static partial class EventBus
{
	private static readonly List<global::ClassA> _subList_ClassA = new List<global::ClassA>(8);

	public static void Subscribe(global::ClassA subscriber)
	{
		lock (_subList_ClassA)
		{
			_subList_ClassA.Add(subscriber);
		}
	}
	public static void Unsubscribe(global::ClassA subscriber)
	{
		lock (_subList_ClassA)
		{
			_subList_ClassA.Remove(subscriber);
		}
	}
}
