//HintName: EventBus_Send__Int32.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoEventBus
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public static partial class EventBus
{
	public static void Send(int value)
	{
		lock (_subList_ClassA)
		{
#if NET5_0_OR_GREATER
			foreach (var receiver in System.Runtime.InteropServices.CollectionsMarshal.AsSpan(_subList_ClassA))
#else
			foreach (var receiver in _subList_ClassA)
#endif
			{
				receiver.Do(value);
			}
		}
		lock (_subList_ClassB)
		{
#if NET5_0_OR_GREATER
			foreach (var receiver in System.Runtime.InteropServices.CollectionsMarshal.AsSpan(_subList_ClassB))
#else
			foreach (var receiver in _subList_ClassB)
#endif
			{
				receiver.Do(value);
			}
		}
	}
}
